/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import projectopoo.*;

/**
 *
 * @author HP
 */
public class AdicionarEntidade extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarEntidade
     */
    private Mundo a;
    private String nome;
    
    public AdicionarEntidade(Mundo a,String nome1) {
        this.a = a;
        nome = nome1;
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        adicionarEntidadeLabel = new javax.swing.JLabel();
        corLabel = new javax.swing.JLabel();
        formaLabel = new javax.swing.JLabel();
        coordenadasLabel = new javax.swing.JLabel();
        raioLabel = new javax.swing.JLabel();
        corComboBox = new javax.swing.JComboBox();
        formaComboBox = new javax.swing.JComboBox();
        classeComboBox = new javax.swing.JComboBox();
        xTextField = new javax.swing.JTextField();
        yTextField = new javax.swing.JTextField();
        raioTextField = new javax.swing.JTextField();
        vidaLabel = new javax.swing.JLabel();
        vidaTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jTextField3.setText("jTextField3");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adicionarEntidadeLabel.setText("Adicionar Entidade");

        corLabel.setText("Cor");

        formaLabel.setText("Forma");

        coordenadasLabel.setText("Coordenadas");

        raioLabel.setText("Raio de visão");

        corComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vermelho","Verde","Amarelo","Azul","Branco","Preto" }));

        formaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Triangular","Quadrangular","Circular","Pentagonal" }));

        classeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agente Aleatório","Agente Hamming","Agente Perto","Objeto Cadeira","Objeto Caixote", "Objeto Mesa","Objeto Outro Objeto","Objeto Secretária" }));
        classeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classeComboBoxActionPerformed(evt);
            }
        });

        raioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raioTextFieldActionPerformed(evt);
            }
        });

        vidaLabel.setText("Vida");

        vidaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidaTextFieldActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(adicionarEntidadeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(formaLabel)
                                        .addComponent(corLabel)
                                        .addComponent(coordenadasLabel)
                                        .addComponent(raioLabel))
                                    .addComponent(vidaLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(corComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(vidaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                            .addComponent(xTextField)
                                            .addComponent(raioTextField))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(yTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(okButton)))))))))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {coordenadasLabel, corLabel, formaLabel, raioLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adicionarEntidadeLabel)
                .addGap(7, 7, 7)
                .addComponent(classeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corLabel)
                    .addComponent(corComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formaLabel)
                    .addComponent(formaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coordenadasLabel)
                    .addComponent(xTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raioLabel)
                    .addComponent(raioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vidaLabel)
                    .addComponent(vidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton))
                .addGap(0, 66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raioTextFieldActionPerformed

    private void vidaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vidaTextFieldActionPerformed

    private void classeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classeComboBoxActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        int raio = Integer.parseInt(raioTextField.getText());
        int vida = Integer.parseInt(vidaTextField.getText());
        int [] coord = {Integer.parseInt(xTextField.getText()),Integer.parseInt(yTextField.getText())};
        String forma = (String)formaComboBox.getSelectedItem();
        String cor = (String)formaComboBox.getSelectedItem();
        if(classeComboBox.getSelectedIndex()==0){
            Aleatorio novo = new Aleatorio(cor,forma,coord,raio,vida);
            a.addAgente(novo);
        }
        else if(classeComboBox.getSelectedIndex()==1){
            Hamming novo = new Hamming(cor,forma,coord,raio,vida);
            a.addAgente(novo);
        }
        else if(classeComboBox.getSelectedIndex()==2){
            Perto novo = new Perto(cor,forma,coord,raio,vida);
            a.addAgente(novo);
        }
        else if(classeComboBox.getSelectedIndex()==3){
            Cadeira novo = new Cadeira(cor,forma,coord);
            a.addObjeto(novo);
        }
        else if(classeComboBox.getSelectedIndex()==4){
            Caixote novo = new Caixote(cor,forma,coord);
            a.addObjeto(novo);
        }
        else if(classeComboBox.getSelectedIndex()==5){
            Mesa novo = new Mesa(cor,forma,coord);
            a.addObjeto(novo);
        }
        else if(classeComboBox.getSelectedIndex()==6){
            OutroObjeto novo = new OutroObjeto(cor,forma,coord,"Outro");
            a.addObjeto(novo);
        }
        else if(classeComboBox.getSelectedIndex()==7){
            Secretaria novo = new Secretaria(cor,forma,coord);
            a.addObjeto(novo);
        }
        Menu novo = new Menu(a,nome);
        novo.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adicionarEntidadeLabel;
    private javax.swing.JComboBox classeComboBox;
    private javax.swing.JLabel coordenadasLabel;
    private javax.swing.JComboBox corComboBox;
    private javax.swing.JLabel corLabel;
    private javax.swing.JComboBox formaComboBox;
    private javax.swing.JLabel formaLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel raioLabel;
    private javax.swing.JTextField raioTextField;
    private javax.swing.JLabel vidaLabel;
    private javax.swing.JTextField vidaTextField;
    private javax.swing.JTextField xTextField;
    private javax.swing.JTextField yTextField;
    // End of variables declaration//GEN-END:variables
}
