/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import projectopoo.*;

/**
 *
 * @author HP
 */
public class ConfigurarAmbiente extends javax.swing.JFrame {

    private Mundo a;
    private String nome;
    public ConfigurarAmbiente(Mundo a, String nome1) {
        this.a = a;
        nome = nome1;
        initComponents();
    }

    public ConfigurarAmbiente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configurarAmbienteLabel = new javax.swing.JLabel();
        criarNovoAmbienteButton = new javax.swing.JToggleButton();
        modificarAmbienteButton = new javax.swing.JToggleButton();
        carregarAmbienteButton = new javax.swing.JToggleButton();
        voltarButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        configurarAmbienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        configurarAmbienteLabel.setText("Configurar ambiente");

        criarNovoAmbienteButton.setText("Criar novo ambiente");
        criarNovoAmbienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarNovoAmbienteButtonActionPerformed(evt);
            }
        });

        modificarAmbienteButton.setText("Modificar ambiente");
        modificarAmbienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAmbienteButtonActionPerformed(evt);
            }
        });

        carregarAmbienteButton.setText("Carregar ambiente");
        carregarAmbienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carregarAmbienteButtonMouseClicked(evt);
            }
        });

        voltarButton.setText("Voltar para o Menu");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configurarAmbienteLabel)
                    .addComponent(modificarAmbienteButton)
                    .addComponent(criarNovoAmbienteButton)
                    .addComponent(carregarAmbienteButton)
                    .addComponent(voltarButton))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {carregarAmbienteButton, configurarAmbienteLabel, criarNovoAmbienteButton, modificarAmbienteButton, voltarButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configurarAmbienteLabel)
                .addGap(18, 18, 18)
                .addComponent(criarNovoAmbienteButton)
                .addGap(18, 18, 18)
                .addComponent(modificarAmbienteButton)
                .addGap(18, 18, 18)
                .addComponent(carregarAmbienteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(voltarButton)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarAmbienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carregarAmbienteButtonMouseClicked
        // TODO add your handling code here:
        CarregarAmbiente novo = new CarregarAmbiente();
        novo.setVisible(true);
        dispose();
    }//GEN-LAST:event_carregarAmbienteButtonMouseClicked

    private void modificarAmbienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAmbienteButtonActionPerformed
        if (a != null) {
            ModificarAmbiente novo = new ModificarAmbiente(a,nome);
            novo.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_modificarAmbienteButtonActionPerformed

    private void criarNovoAmbienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarNovoAmbienteButtonActionPerformed
       CriarNovoAmbiente novo = new CriarNovoAmbiente();
       novo.setVisible(true);
       dispose();
    }//GEN-LAST:event_criarNovoAmbienteButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        Menu novo = new Menu(a,nome);
        novo.setVisible(true);
        dispose();  
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton carregarAmbienteButton;
    private javax.swing.JLabel configurarAmbienteLabel;
    private javax.swing.JToggleButton criarNovoAmbienteButton;
    private javax.swing.JToggleButton modificarAmbienteButton;
    private javax.swing.JToggleButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
