/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import projectopoo.*;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Mundo a;
    private String nome;

    public Menu(Mundo a, String nome) {
        this.a = a;
        this.nome = nome;
        initComponents();

    }
    

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLabel = new javax.swing.JLabel();
        configurarAmbienteButton = new javax.swing.JToggleButton();
        verMemoriaAgenteButton = new javax.swing.JToggleButton();
        estatisticasAgenteButton = new javax.swing.JToggleButton();
        iniciarSimulacaoButton = new javax.swing.JToggleButton();
        sairButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("Menu");

        configurarAmbienteButton.setText("Configurar ambiente");
        configurarAmbienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurarAmbienteButtonActionPerformed(evt);
            }
        });

        verMemoriaAgenteButton.setText("Ver memória agente");
        verMemoriaAgenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMemoriaAgenteButtonActionPerformed(evt);
            }
        });

        estatisticasAgenteButton.setText("Estatísticas agente");
        estatisticasAgenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estatisticasAgenteButtonActionPerformed(evt);
            }
        });

        iniciarSimulacaoButton.setText("Iniciar simulação");
        iniciarSimulacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSimulacaoButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuLabel)
                    .addComponent(verMemoriaAgenteButton)
                    .addComponent(configurarAmbienteButton)
                    .addComponent(estatisticasAgenteButton)
                    .addComponent(iniciarSimulacaoButton)
                    .addComponent(sairButton))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {configurarAmbienteButton, estatisticasAgenteButton, iniciarSimulacaoButton, menuLabel, sairButton, verMemoriaAgenteButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(menuLabel)
                .addGap(18, 18, 18)
                .addComponent(configurarAmbienteButton)
                .addGap(18, 18, 18)
                .addComponent(verMemoriaAgenteButton)
                .addGap(18, 18, 18)
                .addComponent(estatisticasAgenteButton)
                .addGap(18, 18, 18)
                .addComponent(iniciarSimulacaoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(sairButton)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarAmbienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurarAmbienteButtonActionPerformed
        if (this.a != null) {
            ConfigurarAmbiente novo = new ConfigurarAmbiente(a,nome);
            novo.setVisible(true);
            dispose();
        } else {
            ConfigurarAmbiente novo = new ConfigurarAmbiente();
            novo.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_configurarAmbienteButtonActionPerformed

    private void verMemoriaAgenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMemoriaAgenteButtonActionPerformed
        EscolherAgenteMemoria novo = new EscolherAgenteMemoria(this.a,this.nome);
        novo.setVisible(true);
        dispose();
    }//GEN-LAST:event_verMemoriaAgenteButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        try {
            Simulacao.escreverMundo(a,nome);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void estatisticasAgenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estatisticasAgenteButtonActionPerformed
        EscolherAgenteEstatisticas novo = new EscolherAgenteEstatisticas(a,nome);
        novo.setVisible(true);
        dispose();
    }//GEN-LAST:event_estatisticasAgenteButtonActionPerformed

    private void iniciarSimulacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSimulacaoButtonActionPerformed
       IniciarSimulacao novo = new IniciarSimulacao(a,nome);
       //CODIGO PARA A FUNCAO RUN
       novo.setVisible(true);
       dispose();
    }//GEN-LAST:event_iniciarSimulacaoButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton configurarAmbienteButton;
    private javax.swing.JToggleButton estatisticasAgenteButton;
    private javax.swing.JToggleButton iniciarSimulacaoButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JToggleButton sairButton;
    private javax.swing.JToggleButton verMemoriaAgenteButton;
    // End of variables declaration//GEN-END:variables
}
